### ISSUE TITLE
inference should return a list of outputs (order should match that in config file)

### ISSUE THREAD

**Issue by ahmedhosny** [modelhub-ai/modelhub-engine#78]

**Comment by michaelschwier** [comment]
Done. 

Model's inference can either return a list of predictions (even if it is just one) or just a single prediction object (not in a list). The API will take care to wrap a single object into a list. Predictions either have to be a list dicts (label_list) or a numpy array (other allowed output types).
NOTE: I also changed the format of how the API wraps this result into JSON a little: 
https://github.com/modelhub-ai/modelhub-engine/blob/df04380e6c5d288f005a23131e14a2b49aead938/framework/modelhubapi/pythonapi.py#L83-L120

Also extended tests to cover this.
