### ISSUE TITLE
GPU support

### ISSUE THREAD

**Issue by ahmedhosny** [modelhub-ai/modelhub-engine#84]
For models that require a long time for inference, we can have the option to run on nvidia-docker or the like.

**Comment by christophbrgr** [comment]
https://github.com/modelhub-ai/modelhub/pull/50

We still need to add documentation for this.

**Comment by christophbrgr** [comment]
Done with #99 and https://github.com/modelhub-ai/modelhub/tree/75cfb1505bcdca8ebb3c2ae5284623f3bc39feb3 which resolved modelhub-ai/modelhub#54
